# Generated by Cloud66 Starter
FROM ruby:2.1.8
MAINTAINER asghar@akbar.com

RUN apt-get update -qq && apt-get install -y build-essential 

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ENV SIA_TEST $TEST_1

RUN echo $SIA_TEST > /var/siavash.txt
#RUN echo ${SIA_TEST}

ADD . $APP_HOME
